trigger:
  - master

jobs:
- job: Jaco
 timeoutInMinutes: 120
 pool:
   name: 'nvidia-docker-pool'

 steps:
 - task: Bash@3
   inputs:
     workingDirectory: 'docker/ubuntu-bionic-melodic'
     targetType: 'inline'
     script: 'echo $(GITHUB_TOKEN); ./build.sh $(GITHUB_TOKEN)'
 - task: Bash@3
   timeoutInMinutes: 10
   inputs:
     workingDirectory: 'docker/ubuntu-bionic-melodic'
     targetType: 'inline'
     script: './run_docker_container.sh'
   env:
     DISPLAY: :0.0
 - task: Bash@3
   inputs:
     targetType: 'inline'
     script: docker rmi ubuntu1804_dronerescue
